In [1]:
import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

sentences = ['nice great best amazing', 'stop lies', 'pitiful nerd', 'excellent work', 'supreme quality', 'bad', 'highly respectable']
y_train = np.array([1, 0, 0, 1, 1, 0, 1])

Init Plugin
Init Graph Optimizer
Init Kernel


In [2]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts(sentences)
vocab_size = len(tokenizer.word_index) + 1
print(tokenizer.word_index)

X_encoded = tokenizer.texts_to_sequences(sentences)
print(X_encoded)

max_len = max(len(l) for l in X_encoded)
print(max_len)

X_train = np.array(pad_sequences(X_encoded, maxlen=max_len, padding='post'))

print(X_train)

{'nice': 1, 'great': 2, 'best': 3, 'amazing': 4, 'stop': 5, 'lies': 6, 'pitiful': 7, 'nerd': 8, 'excellent': 9, 'work': 10, 'supreme': 11, 'quality': 12, 'bad': 13, 'highly': 14, 'respectable': 15}
[[1, 2, 3, 4], [5, 6], [7, 8], [9, 10], [11, 12], [13], [14, 15]]
4
[[ 1  2  3  4]
 [ 5  6  0  0]
 [ 7  8  0  0]
 [ 9 10  0  0]
 [11 12  0  0]
 [13  0  0  0]
 [14 15  0  0]]


In [3]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Embedding, Flatten
embedding_dim = 4

model = Sequential()
model.add(Embedding(vocab_size, embedding_dim, input_length=max_len))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])
model.fit(X_train, y_train, epochs=100, verbose=2)

Metal device set to: Apple M1

systemMemory: 16.00 GB
maxCacheSize: 5.33 GB



2022-07-12 22:35:08.026940: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2022-07-12 22:35:08.027080: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)
2022-07-12 22:35:09.001386: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:176] None of the MLIR Optimization Passes are enabled (registered 2)
2022-07-12 22:35:09.001793: W tensorflow/core/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz
2022-07-12 22:35:09.189559: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:112] Plugin optimizer for device_type GPU is enabled.


Epoch 1/100
1/1 - 0s - loss: 0.7001 - acc: 0.1429
Epoch 2/100
1/1 - 0s - loss: 0.6989 - acc: 0.2857
Epoch 3/100
1/1 - 0s - loss: 0.6977 - acc: 0.2857
Epoch 4/100
1/1 - 0s - loss: 0.6965 - acc: 0.4286
Epoch 5/100
1/1 - 0s - loss: 0.6953 - acc: 0.4286
Epoch 6/100
1/1 - 0s - loss: 0.6941 - acc: 0.4286
Epoch 7/100
1/1 - 0s - loss: 0.6929 - acc: 0.4286
Epoch 8/100
1/1 - 0s - loss: 0.6917 - acc: 0.4286
Epoch 9/100
1/1 - 0s - loss: 0.6906 - acc: 0.7143
Epoch 10/100
1/1 - 0s - loss: 0.6894 - acc: 0.8571
Epoch 11/100
1/1 - 0s - loss: 0.6882 - acc: 0.8571
Epoch 12/100
1/1 - 0s - loss: 0.6870 - acc: 0.8571
Epoch 13/100
1/1 - 0s - loss: 0.6858 - acc: 0.8571
Epoch 14/100
1/1 - 0s - loss: 0.6846 - acc: 1.0000
Epoch 15/100
1/1 - 0s - loss: 0.6835 - acc: 1.0000
Epoch 16/100
1/1 - 0s - loss: 0.6823 - acc: 1.0000
Epoch 17/100
1/1 - 0s - loss: 0.6811 - acc: 1.0000
Epoch 18/100
1/1 - 0s - loss: 0.6799 - acc: 1.0000
Epoch 19/100
1/1 - 0s - loss: 0.6787 - acc: 1.0000
Epoch 20/100
1/1 - 0s - loss: 0.6775 - a

In [5]:
print(X_train)
print(y_train)

[[ 1  2  3  4]
 [ 5  6  0  0]
 [ 7  8  0  0]
 [ 9 10  0  0]
 [11 12  0  0]
 [13  0  0  0]
 [14 15  0  0]]
[1 0 0 1 1 0 1]


In [6]:
# from urllib.request import urlretrieve, urlopen
# import gzip
# import zipfile

# urlretrieve("http://nlp.stanford.edu/data/glove.6B.zip", filename="glove.6B.zip")
# zf = zipfile.ZipFile('glove.6B.zip')
# zf.extractall() 
# zf.close()

In [ ]:
embedding_dict = dict()
f = open('glove.6B.100d.txt', encoding="utf8")

for line in f:
  print(line)