In [1]:
import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

sentences = ['nice great best amazing', 'stop lies', 'pitiful nerd', 'excellent work', 'supreme quality', 'bad', 'highly respectable']
y_train = np.array([1, 0, 0, 1, 1, 0, 1])

In [2]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts(sentences)
vocab_size = len(tokenizer.word_index) + 1
print(vocab_size)
print(tokenizer.word_index)

X_encoded = tokenizer.texts_to_sequences(sentences)
print(X_encoded)

max_len = max(len(l) for l in X_encoded)
print(max_len)

X_train = np.array(pad_sequences(X_encoded, maxlen=max_len, padding='post'))

print(X_train)

16
{'nice': 1, 'great': 2, 'best': 3, 'amazing': 4, 'stop': 5, 'lies': 6, 'pitiful': 7, 'nerd': 8, 'excellent': 9, 'work': 10, 'supreme': 11, 'quality': 12, 'bad': 13, 'highly': 14, 'respectable': 15}
[[1, 2, 3, 4], [5, 6], [7, 8], [9, 10], [11, 12], [13], [14, 15]]
4
[[ 1  2  3  4]
 [ 5  6  0  0]
 [ 7  8  0  0]
 [ 9 10  0  0]
 [11 12  0  0]
 [13  0  0  0]
 [14 15  0  0]]


In [3]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Embedding, Flatten
embedding_dim = 4

model = Sequential()
model.add(Embedding(vocab_size, embedding_dim, input_length=max_len))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])
model.fit(X_train, y_train, epochs=100, verbose=2)

Epoch 1/100
1/1 - 0s - loss: 0.6967 - acc: 0.5714
Epoch 2/100
1/1 - 0s - loss: 0.6952 - acc: 0.5714
Epoch 3/100
1/1 - 0s - loss: 0.6937 - acc: 0.5714
Epoch 4/100
1/1 - 0s - loss: 0.6922 - acc: 0.5714
Epoch 5/100
1/1 - 0s - loss: 0.6907 - acc: 0.5714
Epoch 6/100
1/1 - 0s - loss: 0.6892 - acc: 0.5714
Epoch 7/100
1/1 - 0s - loss: 0.6878 - acc: 0.7143
Epoch 8/100
1/1 - 0s - loss: 0.6863 - acc: 0.7143
Epoch 9/100
1/1 - 0s - loss: 0.6848 - acc: 0.7143
Epoch 10/100
1/1 - 0s - loss: 0.6833 - acc: 0.7143
Epoch 11/100
1/1 - 0s - loss: 0.6819 - acc: 0.7143
Epoch 12/100
1/1 - 0s - loss: 0.6804 - acc: 0.7143
Epoch 13/100
1/1 - 0s - loss: 0.6790 - acc: 0.7143
Epoch 14/100
1/1 - 0s - loss: 0.6775 - acc: 0.8571
Epoch 15/100
1/1 - 0s - loss: 0.6760 - acc: 0.8571
Epoch 16/100
1/1 - 0s - loss: 0.6746 - acc: 0.8571
Epoch 17/100
1/1 - 0s - loss: 0.6731 - acc: 0.8571
Epoch 18/100
1/1 - 0s - loss: 0.6716 - acc: 0.8571
Epoch 19/100
1/1 - 0s - loss: 0.6702 - acc: 0.8571
Epoch 20/100
1/1 - 0s - loss: 0.6687 - a

In [4]:
print(X_train)
print(y_train)

[[ 1  2  3  4]
 [ 5  6  0  0]
 [ 7  8  0  0]
 [ 9 10  0  0]
 [11 12  0  0]
 [13  0  0  0]
 [14 15  0  0]]
[1 0 0 1 1 0 1]


In [5]:
# from urllib.request import urlretrieve, urlopen
# import gzip
# import zipfile

# urlretrieve("http://nlp.stanford.edu/data/glove.6B.zip", filename="glove.6B.zip")
# zf = zipfile.ZipFile('glove.6B.zip')
# zf.extractall() 
# zf.close()

In [6]:
embedding_dict = dict()
f = open('glove.6B.100d.txt', encoding="utf8")

for line in f:
  word_vector = line.split()
  word = word_vector[0]

  word_vector_arr = np.asarray(word_vector[1:], dtype='float32')
  embedding_dict[word] = word_vector_arr
f.close()

print('%s 개의 Embedding vector가 있습니다' % len(embedding_dict))
  

400000 개의 Embedding vector가 있습니다


In [7]:
embedding_matrix = np.zeros((vocab_size, 100))
# print(embedding_dict['great'])

for word, index in tokenizer.word_index.items():
    vector_value = embedding_dict.get(word)
    if vector_value is not None:
        embedding_matrix[index] = vector_value

embedding_matrix[2]



array([-0.013786  ,  0.38216001,  0.53236002,  0.15261   , -0.29694   ,
       -0.20558   , -0.41846001, -0.58437002, -0.77354997, -0.87866002,
       -0.37858   , -0.18516   , -0.12800001, -0.20584001, -0.22925   ,
       -0.42598999,  0.3725    ,  0.26076999, -1.07019997,  0.62915999,
       -0.091469  ,  0.70348001, -0.4973    , -0.77691001,  0.66044998,
        0.09465   , -0.44893   ,  0.018917  ,  0.33146   , -0.35021999,
       -0.35789001,  0.030313  ,  0.22253001, -0.23236001, -0.19719   ,
       -0.0053125 , -0.25848001,  0.58081001, -0.10705   , -0.17845   ,
       -0.16205999,  0.087086  ,  0.63028997, -0.76648998,  0.51618999,
        0.14072999,  1.01900005, -0.43136001,  0.46138   , -0.43584999,
       -0.47567999,  0.19226   ,  0.36065   ,  0.78987002,  0.088945  ,
       -2.78139997, -0.15366   ,  0.01015   ,  1.17980003,  0.15167999,
       -0.050112  ,  1.26259995, -0.77526999,  0.36030999,  0.95761001,
       -0.11385   ,  0.28035   , -0.02591   ,  0.31246001, -0.15

In [15]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Embedding, Flatten

output_dim = 100

model = Sequential()
e = Embedding(vocab_size, output_dim, weights=[embedding_matrix], input_length=max_len, trainable=True)
model.add(e)
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))
model.compile(optimizer='adam', loss="binary_crossentropy", metrics=['acc'])
model.fit(X_train, y_train, epochs=100, verbose=2)

Epoch 1/100
1/1 - 0s - loss: 0.9633 - acc: 0.1429
Epoch 2/100
1/1 - 0s - loss: 0.9248 - acc: 0.1429
Epoch 3/100
1/1 - 0s - loss: 0.8874 - acc: 0.1429
Epoch 4/100
1/1 - 0s - loss: 0.8510 - acc: 0.1429
Epoch 5/100
1/1 - 0s - loss: 0.8157 - acc: 0.2857
Epoch 6/100
1/1 - 0s - loss: 0.7817 - acc: 0.2857
Epoch 7/100
1/1 - 0s - loss: 0.7489 - acc: 0.2857
Epoch 8/100
1/1 - 0s - loss: 0.7173 - acc: 0.4286
Epoch 9/100
1/1 - 0s - loss: 0.6871 - acc: 0.4286
Epoch 10/100
1/1 - 0s - loss: 0.6582 - acc: 0.4286
Epoch 11/100
1/1 - 0s - loss: 0.6307 - acc: 0.5714
Epoch 12/100
1/1 - 0s - loss: 0.6045 - acc: 0.5714
Epoch 13/100
1/1 - 0s - loss: 0.5797 - acc: 0.7143
Epoch 14/100
1/1 - 0s - loss: 0.5561 - acc: 0.7143
Epoch 15/100
1/1 - 0s - loss: 0.5338 - acc: 0.8571
Epoch 16/100
1/1 - 0s - loss: 0.5127 - acc: 0.8571
Epoch 17/100
1/1 - 0s - loss: 0.4927 - acc: 1.0000
Epoch 18/100
1/1 - 0s - loss: 0.4739 - acc: 1.0000
Epoch 19/100
1/1 - 0s - loss: 0.4560 - acc: 1.0000
Epoch 20/100
1/1 - 0s - loss: 0.4391 - a