In [22]:
import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

sentences = ['nice great best amazing', 'stop lies', 'pitiful nerd', 'excellent work', 'supreme quality', 'bad', 'highly respectable']
y_train = np.array([1, 0, 0, 1, 1, 0, 1])

In [23]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts(sentences)
vocab_size = len(tokenizer.word_index) + 1
print(tokenizer.word_index)

X_encoded = tokenizer.texts_to_sequences(sentences)
print(X_encoded)

max_len = max(len(l) for l in X_encoded)
print(max_len)

X_train = np.array(pad_sequences(X_encoded, maxlen=max_len, padding='post'))

print(X_train)

{'nice': 1, 'great': 2, 'best': 3, 'amazing': 4, 'stop': 5, 'lies': 6, 'pitiful': 7, 'nerd': 8, 'excellent': 9, 'work': 10, 'supreme': 11, 'quality': 12, 'bad': 13, 'highly': 14, 'respectable': 15}
[[1, 2, 3, 4], [5, 6], [7, 8], [9, 10], [11, 12], [13], [14, 15]]
4
[[ 1  2  3  4]
 [ 5  6  0  0]
 [ 7  8  0  0]
 [ 9 10  0  0]
 [11 12  0  0]
 [13  0  0  0]
 [14 15  0  0]]


In [24]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Embedding, Flatten
embedding_dim = 4

model = Sequential()
model.add(Embedding(vocab_size, embedding_dim, input_length=max_len))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])
model.fit(X_train, y_train, epochs=100, verbose=2)

Epoch 1/100


2022-07-12 00:11:47.332998: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:176] None of the MLIR Optimization Passes are enabled (registered 2)
2022-07-12 00:11:47.333447: W tensorflow/core/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz
2022-07-12 00:11:47.516828: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:112] Plugin optimizer for device_type GPU is enabled.


1/1 - 2s - loss: 0.6851 - acc: 0.5714
Epoch 2/100
1/1 - 0s - loss: 0.6834 - acc: 0.7143
Epoch 3/100
1/1 - 0s - loss: 0.6818 - acc: 0.7143
Epoch 4/100
1/1 - 0s - loss: 0.6801 - acc: 0.7143
Epoch 5/100
1/1 - 0s - loss: 0.6784 - acc: 0.8571
Epoch 6/100
1/1 - 0s - loss: 0.6768 - acc: 0.8571
Epoch 7/100
1/1 - 0s - loss: 0.6751 - acc: 0.8571
Epoch 8/100
1/1 - 0s - loss: 0.6735 - acc: 0.8571
Epoch 9/100
1/1 - 0s - loss: 0.6718 - acc: 0.8571
Epoch 10/100
1/1 - 0s - loss: 0.6702 - acc: 0.8571
Epoch 11/100
1/1 - 0s - loss: 0.6685 - acc: 0.8571
Epoch 12/100
1/1 - 0s - loss: 0.6668 - acc: 0.8571
Epoch 13/100
1/1 - 0s - loss: 0.6652 - acc: 0.8571
Epoch 14/100
1/1 - 0s - loss: 0.6635 - acc: 1.0000
Epoch 15/100
1/1 - 0s - loss: 0.6618 - acc: 1.0000
Epoch 16/100
1/1 - 0s - loss: 0.6601 - acc: 1.0000
Epoch 17/100
1/1 - 0s - loss: 0.6585 - acc: 1.0000
Epoch 18/100
1/1 - 0s - loss: 0.6568 - acc: 1.0000
Epoch 19/100
1/1 - 0s - loss: 0.6551 - acc: 1.0000
Epoch 20/100
1/1 - 0s - loss: 0.6534 - acc: 1.0000
E