In [18]:
import tensorflow as tf

w = tf.Variable(2.)
def f(w):
  y = w**2
  z = 2*y + 5
  return z


with tf.GradientTape() as tape:
  z = f(w)

gradients = tape.gradient(z, [w])
print(gradients)
# 2w**2+b

#가설 함수
w = tf.Variable(4.0)
b = tf.Variable(1.0)

@tf.function
def hypothesis(x):
  return w*x+b

x_test = [3.5, 5, 5.5, 6]

print(hypothesis(x_test).numpy())

#손실 함수
@tf.function
def mse_loss(y_pred, y):
  return tf.reduce_mean(tf.square(y_pred - y))

x = [1, 2, 3, 4, 5, 6, 7, 8, 9] # 공부하는 시간
y = [11, 22, 33, 44, 53, 66, 77, 87, 95] # 각 공부하는 시간에 맵핑되는 성적

optimizer = tf.optimizers.SGD(0.01)



[<tf.Tensor: shape=(), dtype=float32, numpy=8.0>]
[15. 21. 23. 25.]
tf.Tensor([ 5.  9. 13. 17. 21. 25. 29. 33. 37.], shape=(9,), dtype=float32)


In [21]:
for i in range(301):
  
  with tf.GradientTape() as tape:
    y_pred = hypothesis(x)
    print(y_pred)
    cost = mse_loss

tf.Tensor([ 5.  9. 13. 17. 21. 25. 29. 33. 37.], shape=(9,), dtype=float32)
tf.Tensor([ 5.  9. 13. 17. 21. 25. 29. 33. 37.], shape=(9,), dtype=float32)
tf.Tensor([ 5.  9. 13. 17. 21. 25. 29. 33. 37.], shape=(9,), dtype=float32)
tf.Tensor([ 5.  9. 13. 17. 21. 25. 29. 33. 37.], shape=(9,), dtype=float32)
tf.Tensor([ 5.  9. 13. 17. 21. 25. 29. 33. 37.], shape=(9,), dtype=float32)
tf.Tensor([ 5.  9. 13. 17. 21. 25. 29. 33. 37.], shape=(9,), dtype=float32)
tf.Tensor([ 5.  9. 13. 17. 21. 25. 29. 33. 37.], shape=(9,), dtype=float32)
tf.Tensor([ 5.  9. 13. 17. 21. 25. 29. 33. 37.], shape=(9,), dtype=float32)
tf.Tensor([ 5.  9. 13. 17. 21. 25. 29. 33. 37.], shape=(9,), dtype=float32)
tf.Tensor([ 5.  9. 13. 17. 21. 25. 29. 33. 37.], shape=(9,), dtype=float32)
tf.Tensor([ 5.  9. 13. 17. 21. 25. 29. 33. 37.], shape=(9,), dtype=float32)
tf.Tensor([ 5.  9. 13. 17. 21. 25. 29. 33. 37.], shape=(9,), dtype=float32)
tf.Tensor([ 5.  9. 13. 17. 21. 25. 29. 33. 37.], shape=(9,), dtype=float32)
tf.Tensor([ 