In [1]:
from konlpy.tag import Okt
from hanspell import spell_checker


okt = Okt()


tokens = okt.morphs('나는 자연어 처리를 배운다')

word_to_index = {word : index for index, word in enumerate(tokens) }



def one_hot_encoding(word, word_to_index):
    
    one_hot_vector = [0]*(len(word_to_index))
    index = word_to_index[word]
    one_hot_vector[index] = 1
    
    return one_hot_vector


one_hot_encoding('자연어', word_to_index)


text = "나랑 점심 먹으러 갈래 점심 메뉴는 햄버거 갈래 갈래 햄버거 최고야"
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.utils import to_categorical

tokenizer = Tokenizer()
tokenizer.fit_on_texts([text])
# print(tokenizer.word_index)

sub_text = "점심 먹으러 갈래 메뉴는 햄버거 최고야"

encoded = tokenizer.texts_to_sequences([sub_text])
# print(encoded)

one_hot = to_categorical(encoded)
# print(one_hot)

import pandas as  pd
import numpy as np
from sklearn.model_selection import train_test_split


values = [['당신에게 드리는 마지막 혜택!', 1],
['내일 뵐 수 있을지 확인 부탁드...', 0],
['도연씨. 잘 지내시죠? 오랜만입...', 0],
['(광고) AI로 주가를 예측할 수 있다!', 1]]
columns = ['메일 본문', '스팸 메일 유무']

df = pd.DataFrame(values, columns=columns)
df

X = df['메일 본문']
y = df['스팸 메일 유무']

# print(X.to_list())
# print(y.to_list())



X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1234)




sent = "김철수는극중두인격의사나이이광수역을맡았다.철수는한국유일의태권도전승자를가리는결전의날을앞두고10년간함께훈련한사형인유연재(김광수분)를찾으러속세로내려온인물이다."
spelled_sent = spell_checker.check(sent)

hanspell_sent = spelled_sent.checked


# 마지막 열을 제외하고 X데이터에 저장합니다. 마지막 열만을 y데이터에 저장합니다.




Init Plugin
Init Graph Optimizer
Init Kernel


In [2]:
import urllib.request
import tensorflow as tf
print(tf.__version__)
from soynlp import DoublespaceLineCorpus
from soynlp.word import WordExtractor

urllib.request.urlretrieve("https://raw.githubusercontent.com/lovit/soynlp/master/tutorials/2016-10-20.txt", filename="2016-10-20.txt")


corpus = DoublespaceLineCorpus("2016-10-20.txt")

2.5.0


In [3]:
i =0

for document in corpus:
  if len(document) > i:
    i = i + 1
  if i == 3:
    break

word_extractor = WordExtractor()
word_extractor.train(corpus)
word_score_table = word_extractor.extract()



training was done. used memory 1.625 Gb
all cohesion probabilities was computed. # words = 223348
all branching entropies was computed # words = 361598
all accessor variety was computed # words = 361598


In [4]:
word_score_table["반포한"].cohesion_forward


0.08838002913645132

In [5]:
from soynlp.tokenizer import LTokenizer

scores =  {word:score.cohesion_forward for word, score in word_score_table.items()}

l_tokenizer = LTokenizer(scores=scores)
l_tokenizer.tokenize("국제사회와 우리의 노력들로 범죄를 척결하자", flatten=False)

from soynlp.tokenizer import MaxScoreTokenizer
maxscore_tokenizer = MaxScoreTokenizer(scores=scores)
maxscore_tokenizer.tokenize("국제사회와우리의노력들로범죄를척결하자") 
  

['국제사회', '와', '우리', '의', '노력', '들로', '범죄', '를', '척결', '하자']

In [6]:
from soynlp.normalizer import *
emo = emoticon_normalize("앜ㅋㅋㅋㅋ이영화존잼쓰ㅠㅠㅠㅠㅠ", num_repeats=2)
print(emo)
print(repeat_normalize('와하하하하하하하하하핫', num_repeats=2))

아ㅋㅋ영화존잼쓰ㅠㅠ
와하하핫


In [7]:

from konlpy.tag import Okt

okt = Okt()

def build_bag_of_words(document):
  # 온점 제거 및 형태소 분석
  document = document.replace('.', '')
  tokenized_document = okt.morphs(document)

  word_to_index = {}
  bow = []

  for word in tokenized_document:  
    if word not in word_to_index.keys():
      word_to_index[word] = len(word_to_index)  
      # BoW에 전부 기본값 1을 넣는다.
      bow.insert(len(word_to_index) - 1, 1)
    else:
      # 재등장하는 단어의 인덱스
      index = word_to_index.get(word)
      print(index)
      # 재등장한 단어는 해당하는 인덱스의 위치에 1을 더한다.
      bow[index] = bow[index] + 1

  return word_to_index, bow

doc1 = "정부가 발표하는 물가상승률과 소비자가 느끼는 물가상승률은 다르다."
vocab, bow = build_bag_of_words(doc1)
print('vocabulary :', vocab)
print('bag of words vector :', bow)

1
4
vocabulary : {'정부': 0, '가': 1, '발표': 2, '하는': 3, '물가상승률': 4, '과': 5, '소비자': 6, '느끼는': 7, '은': 8, '다르다': 9}
bag of words vector : [1, 2, 1, 1, 2, 1, 1, 1, 1, 1]


In [8]:
from sklearn.feature_extraction.text import CountVectorizer

corpus = ['정부가 발표하는 물가상승률 소비자가 느끼는 물가상승률 다르다.']
vector = CountVectorizer()

print('bag of words vector :', vector.fit_transform(corpus).toarray()) 

# 각 단어의 인덱스가 어떻게 부여되었는지를 출력
print('vocabulary :',vector.vocabulary_)


bag of words vector : [[1 1 2 1 1 1]]
vocabulary : {'정부가': 5, '발표하는': 3, '물가상승률': 2, '소비자가': 4, '느끼는': 0, '다르다': 1}


In [9]:
import pandas as pd
from math import log

docs = [
  '먹고 싶은 사과',
  '먹고 싶은 바나나',
  '길고 노란 바나나 바나나',
  '저는 과일이 좋아요'
]

vocab = list(set(w for doc in docs for w in doc.split()))
vocab.sort()
print(vocab)

N = len(docs) #문서의 수

def tf(t, d):
    return d.count(t)

def idf(t):
    df = 0
    for doc in docs:
        
        df += t in doc
        
    return log(N/(df+1))

def tfidf(t, d):
    return tf(t,d)* idf(t)


result = []

for i in range(N):
    result.append([])
    d = docs[i]
    for j in range(len(vocab)):
        t = vocab[j]
        tf(t,d)
        result[-1].append(tf(t,d))

tf_ = pd.DataFrame(result, columns=vocab)

tf_


    

['과일이', '길고', '노란', '먹고', '바나나', '사과', '싶은', '저는', '좋아요']


과일이  길고  노란  먹고  바나나  사과  싶은  저는  좋아요
0    0   0   0   1    0   1   1   0    0
1    0   0   0   1    1   0   1   0    0
2    0   1   1   0    2   0   0   0    0
3    1   0   0   0    0   0   0   1    1

In [10]:
result = []
for j in range(len(vocab)):
    t = vocab[j]
    # print(t)
    result.append(idf(t))
print(result)
idf_ = pd.DataFrame(result, index=vocab, columns=["IDF"])

idf_

[0.6931471805599453, 0.6931471805599453, 0.6931471805599453, 0.28768207245178085, 0.28768207245178085, 0.6931471805599453, 0.28768207245178085, 0.6931471805599453, 0.6931471805599453]


IDF
과일이  0.693147
길고   0.693147
노란   0.693147
먹고   0.287682
바나나  0.287682
사과   0.693147
싶은   0.287682
저는   0.693147
좋아요  0.693147

In [11]:
result = []
for i in range(N):
    result.append([])
    d = docs[i]
    for j in range(len(vocab)):
        t = vocab[j]
        result[-1].append(tfidf(t, d))
    
tfidf_ = pd.DataFrame(result, columns=vocab)
tfidf_

과일이        길고        노란        먹고       바나나        사과        싶은  \
0  0.000000  0.000000  0.000000  0.287682  0.000000  0.693147  0.287682   
1  0.000000  0.000000  0.000000  0.287682  0.287682  0.000000  0.287682   
2  0.000000  0.693147  0.693147  0.000000  0.575364  0.000000  0.000000   
3  0.693147  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   

         저는       좋아요  
0  0.000000  0.000000  
1  0.000000  0.000000  
2  0.000000  0.000000  
3  0.693147  0.693147

In [12]:
from sklearn.feature_extraction.text import CountVectorizer

corpus = [
    'you know I want your love',
    'I like you',
    'what should I do ',    
]


vector = CountVectorizer()

print(vector.fit_transform(corpus).toarray())
print(vector.vocabulary_)

[[0 1 0 1 0 1 0 1 1]
 [0 0 1 0 0 0 0 1 0]
 [1 0 0 0 1 0 1 0 0]]
{'you': 7, 'know': 1, 'want': 5, 'your': 8, 'love': 3, 'like': 2, 'what': 6, 'should': 4, 'do': 0}


In [13]:
from sklearn.feature_extraction.text import TfidfVectorizer
corpus = [
    'you know I want your love',
    'I like you',
    'what should I do ',    
]

tfidf = TfidfVectorizer().fit(corpus)

# print(tfidf.transform(corpus).toarray())
print(tfidf.vocabulary_)
test = tfidf.transform(corpus).toarray()
test_ = pd.DataFrame(test)

test_




{'you': 7, 'know': 1, 'want': 5, 'your': 8, 'love': 3, 'like': 2, 'what': 6, 'should': 4, 'do': 0}


0         1         2         3        4         5        6  \
0  0.00000  0.467351  0.000000  0.467351  0.00000  0.467351  0.00000   
1  0.00000  0.000000  0.795961  0.000000  0.00000  0.000000  0.00000   
2  0.57735  0.000000  0.000000  0.000000  0.57735  0.000000  0.57735   

          7         8  
0  0.355432  0.467351  
1  0.605349  0.000000  
2  0.000000  0.000000

In [14]:
import numpy as np
from numpy import dot
from numpy.linalg import norm

from sklearn.feature_extraction.text import CountVectorizer

corpus = [
    '저는 사과 좋아요',
    '저는 바나나 좋아요',
    '저는 바나나 좋아요'
]


vector = CountVectorizer()

docs = vector.fit_transform(corpus).toarray()

print(docs)

def cos_sim(A, B):
    return dot(A, B)/(norm(A)*norm(B))

print('문서 1과 문서2의 유사도 :',cos_sim(docs[0], docs[1]))
print('문서 1과 문서3의 유사도 :',cos_sim(docs[0], docs[2]))
print('문서 2와 문서3의 유사도 :',cos_sim(docs[1], docs[2]))

[[0 1 1 1]
 [1 0 1 1]
 [1 0 1 1]]
문서 1과 문서2의 유사도 : 0.6666666666666667
문서 1과 문서3의 유사도 : 0.6666666666666667
문서 2와 문서3의 유사도 : 1.0000000000000002


In [15]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer

from sklearn.metrics.pairwise import cosine_similarity

data = pd.read_csv('../file/movies_metadata.csv', low_memory=False)

data = data.head(20000)



print(data['overview'].isnull().sum())
data['overview'] = data['overview'].fillna('')
print(data['overview'].isnull().sum())

# vector = CountVectorizer()

# print(vector.fit_transform(data['overview']).toarray())
# print(vector.vocabulary_)

tfidf = TfidfVectorizer(stop_words='english')
tfidf_matrix = tfidf.fit_transform(data['overview'])
# print(tfidf.vocabulary_)
print(tfidf_matrix.shape)

# Led by Woody, Andy's toys live happily in his room until Andy's birthday brings Buzz Lightyear onto the scene. Afraid of losing his place in Andy's heart, Woody plots against Buzz. But when circumstances separate Buzz and Woody from their owner, the duo eventually learns to put aside their differences.



cosine_sim = cosine_similarity(tfidf_matrix, tfidf_matrix)
print(cosine_sim.shape)




135
0
(20000, 47487)
(20000, 20000)


In [16]:
title_to_index = dict(zip(data['title'], data.index))

def get_recommendations(title, cosine_sim=cosine_sim):
    idx = title_to_index[title]
    print(idx)
    sim_scroes = list(enumerate(cosine_sim[idx]))

    sim_scores = sorted(sim_scroes, key=lambda x: x[1], reverse=True)


    sim_scores = sim_scores[1:11]

    movie_indices = [idx[0] for idx in sim_scores]


    return data['title'].iloc[movie_indices]
    


get_recommendations('The Dark Knight Rises')

18252


12481                            The Dark Knight
150                               Batman Forever
1328                              Batman Returns
15511                 Batman: Under the Red Hood
585                                       Batman
9230          Batman Beyond: Return of the Joker
18035                           Batman: Year One
19792    Batman: The Dark Knight Returns, Part 1
3095                Batman: Mask of the Phantasm
10122                              Batman Begins
Name: title, dtype: object

In [17]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer

from sklearn.metrics.pairwise import cosine_similarity

data = pd.read_csv('../file/movies_metadata.csv', low_memory=False)

data = data.head(20000)
data['overview'] = data['overview'].fillna('')


tfidf = TfidfVectorizer(stop_words='english')
tfidf_matrix = tfidf.fit_transform(data['overview'])

cosine_sim = cosine_similarity(tfidf_matrix, tfidf_matrix)

title_to_index = dict(zip(data['title'], data.index))

def get_recommendations(title, cosine_sim=cosine_sim):
    idx = title_to_index[title]
    
    sim_scores = list(enumerate(cosine_sim[idx]))
    
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
    
    sim_scores = sim_scores[1:11]

    movie_indices = [idx[0] for idx in sim_scores]
    
    return data['title'].iloc[movie_indices]


get_recommendations('Toy Story')
# 여러가지 유사도 기법


15348               Toy Story 3
2997                Toy Story 2
10301    The 40 Year Old Virgin
8327                  The Champ
1071      Rebel Without a Cause
11399    For Your Consideration
1932                  Condorman
3057            Man on the Moon
485                      Malice
11606              Factory Girl
Name: title, dtype: object