In [8]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import SimpleRNN

model = Sequential()
model.add(SimpleRNN(3, batch_input_shape=(8,2,10), return_sequences=True))
model.summary()

Model: "sequential_7"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
simple_rnn_11 (SimpleRNN)    (8, 2, 3)                 42        
Total params: 42
Trainable params: 42
Non-trainable params: 0
_________________________________________________________________


In [114]:
import numpy as np

timesteps = 10
input_dim = 4
hidden_units = 8

inputs = np.random.random((timesteps, input_dim))
print(inputs)
print('='*100)
hidden_state_t = np.zeros((hidden_units,))
print(hidden_state_t)

[[0.51934522 0.52219653 0.3068383  0.60519782]
 [0.27818608 0.61649596 0.96719814 0.80470354]
 [0.12790928 0.67685479 0.88143731 0.39026095]
 [0.92331672 0.46493794 0.19177105 0.31896353]
 [0.46199471 0.71692669 0.12857274 0.0497545 ]
 [0.79942763 0.56792586 0.65820331 0.05850912]
 [0.67750374 0.13916416 0.72391966 0.70226267]
 [0.63438886 0.50537554 0.08443341 0.44220011]
 [0.24722578 0.81692898 0.31070611 0.59082416]
 [0.49371902 0.07336783 0.129965   0.6005984 ]]
[0. 0. 0. 0. 0. 0. 0. 0.]


In [97]:
Wx = np.random.random((hidden_units,input_dim))
Wh = np.random.random((hidden_units,hidden_units))
b = np.random.random((hidden_units))
print('가중치 Wx의 크기(shape) :',np.shape(Wx))
print('가중치 Wh의 크기(shape) :',np.shape(Wh))
print('편향의 크기(shape) :',np.shape(b))

[0.49795314 0.86180741 0.07169279 0.14391862 0.46109477 0.13962422
 0.90184961 0.20607008]
가중치 Wx의 크기(shape) : (8, 4)
가중치 Wh의 크기(shape) : (8, 8)
편향의 크기(shape) : (8,)


In [119]:
total_hidden_states = []

for input_t in inputs:
    #ht = Wx * Xt + Wh * Ht-1 + b
    # print(input_t)
    out_t = np.tanh(np.dot(Wx,input_t) + np.dot(Wh, hidden_state_t) + b)
    
    
    total_hidden_states.append(list(out_t))
    hidden_state_t = out_t
    
total_hidden_states = np.stack(total_hidden_states, axis=0)
# (timesteps, output_dim)
print('모든 시점의 은닉 상태 :')
print(total_hidden_states)


모든 시점의 은닉 상태 :
[[0.99999553 0.99994852 0.99996558 0.99999548 0.99998535 0.99955669
  0.99998998 0.99999798]
 [0.9999988  0.99998209 0.99997761 0.99999542 0.99999005 0.99986841
  0.99999092 0.99999834]
 [0.99999839 0.99997114 0.99993803 0.99998867 0.99997928 0.99980559
  0.9999849  0.99999762]
 [0.99999352 0.99994025 0.99996261 0.99999614 0.99998684 0.99953694
  0.99999289 0.99999869]
 [0.99999436 0.99991902 0.99989866 0.99998834 0.9999691  0.99929345
  0.99998749 0.99999769]
 [0.99999702 0.99996462 0.99994485 0.99999308 0.99998504 0.99978662
  0.99999211 0.99999885]
 [0.99999555 0.99996011 0.99997343 0.99999665 0.99998974 0.99978714
  0.99998687 0.99999808]
 [0.99999293 0.99992467 0.99995492 0.99999503 0.99998228 0.99933406
  0.99998977 0.99999794]
 [0.99999734 0.99995795 0.99996001 0.99999349 0.99998202 0.99954218
  0.99999075 0.99999783]
 [0.99998544 0.99987013 0.99994111 0.99999447 0.99997706 0.99916787
  0.99997356 0.99999573]]


In [120]:
model = Sequential()
model.add(SimpleRNN(hidden_units, input_length=10, input_dim=5, return_sequences=True))
model.add(SimpleRNN(hidden_units, return_sequences=True))

In [123]:
from tensorflow.keras.layers import Bidirectional, Embedding, Dense
timesteps = 10 #input length
input_dim = 5

model = Sequential()
model.add(Bidirectional(SimpleRNN(hidden_units, return_sequences=True), input_shape=(timesteps, input_dim)))



In [126]:
vocab_size = 5000
embedding_dim = 100
hidden_units = 128
b= 1

model = Sequential()
model.add(Embedding(vocab_size, embedding_dim))
model.add(SimpleRNN(hidden_units))
model.add(Dense(1, activation='sigmoid'))
model.summary()

Model: "sequential_14"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_2 (Embedding)      (None, None, 100)         500000    
_________________________________________________________________
simple_rnn_19 (SimpleRNN)    (None, 128)               29312     
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 129       
Total params: 529,441
Trainable params: 529,441
Non-trainable params: 0
_________________________________________________________________


In [251]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import SimpleRNN, LSTM, Bidirectional

train_X = [[[0.1, 4.2, 1.5, 1.1, 2.8], [1.0, 3.1, 2.5, 0.7, 1.1], [0.3, 2.1, 1.5, 2.1, 0.1], [2.2, 1.4, 0.5, 0.9, 1.1]]]

train_X = np.array(train_X, dtype=np.float32)
hidden_units = 3
rnn = SimpleRNN(hidden_units, return_sequences=True)
hidden_state = rnn(train_X)

print('hidden state: {}, shape: {}'.format(hidden_state, hidden_state.shape))


hidden state: [[[-0.9986801  -0.85428095  0.99890846]
  [-0.99934036  0.5494923   0.9948631 ]
  [-0.9533791  -0.01486525  0.98745185]
  [-0.9965948   0.9881755   0.94507617]]], shape: (1, 4, 3)


In [252]:
lstm = LSTM(hidden_units)